name: nobody-chat-server
services:
  server:
    build:
      context: .
      target: final
    container_name: nobody-chat-server
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - RUST_LOG=info
      - ALLOW_URLS=["http://localhost:3001"]
